// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:tiratana_upasana_app/models/meditation_record.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MeditationRecordAdapter());
  }
}
