// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_sync_flutter_libs/objectbox_sync_flutter_libs.dart';

import 'models/app_cache.dart';
import 'models/meditation_record.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5086123549889689050),
    name: 'MeditationRecord',
    lastPropertyId: const obx_int.IdUid(6, 4814803367314923530),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2005689600732150472),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 630209800366612025),
        name: 'meditationStartTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4372376489384304559),
        name: 'meditationDuration',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4814803367314923530),
        name: 'meditationNote',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6541389482037926505),
    name: 'AppCache',
    lastPropertyId: const obx_int.IdUid(3, 7779849699668132475),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5199511701524115266),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6392566968567848402),
        name: 'cachedMeditationWatchStartTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7779849699668132475),
        name: 'chantJsonPath',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 6541389482037926505),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [493462384748768008, 2947443263200406372],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    MeditationRecord: obx_int.EntityDefinition<MeditationRecord>(
      model: _entities[0],
      toOneRelations: (MeditationRecord object) => [],
      toManyRelations: (MeditationRecord object) => {},
      getId: (MeditationRecord object) => object.id,
      setId: (MeditationRecord object, int id) {
        object.id = id;
      },
      objectToFB: (MeditationRecord object, fb.Builder fbb) {
        final meditationNoteOffset = fbb.writeString(object.meditationNote);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(3, object.meditationStartTime.millisecondsSinceEpoch);
        fbb.addInt64(4, object.meditationDuration);
        fbb.addOffset(5, meditationNoteOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final meditationStartTimeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final meditationDurationParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final meditationNoteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final object = MeditationRecord(
          meditationStartTime: meditationStartTimeParam,
          meditationDuration: meditationDurationParam,
          meditationNote: meditationNoteParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    AppCache: obx_int.EntityDefinition<AppCache>(
      model: _entities[1],
      toOneRelations: (AppCache object) => [],
      toManyRelations: (AppCache object) => {},
      getId: (AppCache object) => object.id,
      setId: (AppCache object, int id) {
        object.id = id;
      },
      objectToFB: (AppCache object, fb.Builder fbb) {
        final chantJsonPathOffset = fbb.writeString(object.chantJsonPath);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addInt64(
          1,
          object.cachedMeditationWatchStartTime?.millisecondsSinceEpoch,
        );
        fbb.addOffset(2, chantJsonPathOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final cachedMeditationWatchStartTimeValue = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 6);
        final cachedMeditationWatchStartTimeParam =
            cachedMeditationWatchStartTimeValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(
                  cachedMeditationWatchStartTimeValue,
                );
        final chantJsonPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = AppCache(
          cachedMeditationWatchStartTime: cachedMeditationWatchStartTimeParam,
          chantJsonPath: chantJsonPathParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [MeditationRecord] entity fields to define ObjectBox queries.
class MeditationRecord_ {
  /// See [MeditationRecord.id].
  static final id = obx.QueryIntegerProperty<MeditationRecord>(
    _entities[0].properties[0],
  );

  /// See [MeditationRecord.meditationStartTime].
  static final meditationStartTime = obx.QueryDateProperty<MeditationRecord>(
    _entities[0].properties[1],
  );

  /// See [MeditationRecord.meditationDuration].
  static final meditationDuration = obx.QueryIntegerProperty<MeditationRecord>(
    _entities[0].properties[2],
  );

  /// See [MeditationRecord.meditationNote].
  static final meditationNote = obx.QueryStringProperty<MeditationRecord>(
    _entities[0].properties[3],
  );
}

/// [AppCache] entity fields to define ObjectBox queries.
class AppCache_ {
  /// See [AppCache.id].
  static final id = obx.QueryIntegerProperty<AppCache>(
    _entities[1].properties[0],
  );

  /// See [AppCache.cachedMeditationWatchStartTime].
  static final cachedMeditationWatchStartTime = obx.QueryDateProperty<AppCache>(
    _entities[1].properties[1],
  );

  /// See [AppCache.chantJsonPath].
  static final chantJsonPath = obx.QueryStringProperty<AppCache>(
    _entities[1].properties[2],
  );
}
