name: tiratana_upasana_app
description: A Flutter application containing Buddhism related services.
version: 1.0.0+4
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_html: ^3.0.0
  flutter_localizations:
    sdk: flutter
  formz: ^0.8.0
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  intl: ^0.19.0
  markdown: ^7.3.0
  objectbox: ^4.2.0
  objectbox_sync_flutter_libs: any
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.8.2
  mocktail: ^1.0.4
  objectbox_generator: any
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
